### ISSUE TITLE
Use of pretrained PixelCNN++

### ISSUE THREAD

**Issue by erikdao** [chenlin9/Autoregressive-Modeling-with-Distribution-Smoothing#2]
Hi,
First off, thank you very much for sharing the code.
I'm wondering if the author initialized the weights of PixelCNN++ with a pretrained model or train it from scratch?

**Comment by chenlin9** [comment]
Hello, thank you for the question. We initialized the weights of PixelCNN++ from scratch.

**Comment by erikdao** [comment]
Thanks for the answer @chenlin9
